services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8070:80"
    container_name: fusionpact-frontend
    restart: unless-stopped
    networks:
      - fusionpact-network
    environment:
      - NODE_ENV=production

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    container_name: fusionpact-backend
    restart: unless-stopped
    volumes:
      # Data persistence for user data
      - backend-data:/app/app/data
    environment:
      - PYTHONPATH=/app
      - ENV=production
    networks:
      - fusionpact-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Named volumes for data persistence
volumes:
  backend-data:
    driver: local

# Custom network for service communication
networks:
  fusionpact-network:
    driver: bridge
